apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nikodemwrona-dev-tls
  namespace: nikodemwrona-dev
spec:
  secretName: nikodemwrona-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nikodemwrona.dev
  dnsNames:
    - nikodemwrona.dev
