apiVersion: v1
kind: Service
metadata:
  name: nikodemwrona-dev
  namespace: website
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: nikodemwrona-dev
  sessionAffinity: None
  type: ClusterIP