name: Build & Push to Github Packages
on:
  push:
    branches:
      - master

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build nikodemwrona.dev Docker image
        run: |
          docker build --tag "ghcr.io/nikodem-wrona/nikodemwrona.dev/nikodemwrona.dev:latest" .
      - name: Push nikodemwrona.dev  Docker image
        run: |
          docker push "ghcr.io/nikodem-wrona/nikodemwrona.dev/nikodemwrona.dev:latest"
